title: FixitFaster Systems Status Page
languageCode: en
params:
  shortDateFormat: 15:04 — Jan 2
  meta_description: This status page provides updated information about our
    systems normal operation, incidents that may happen and their resolution.
  systems:
    - name: Fix it Faster Website
      description: Public facing website for Fix It Faster
      link: https://www.fixitfaster.com/
    - name: Fix It Faster Server
      description: Fix It Faster backend server
      link: https://api.fixitfaster.com/
  dateFormat: January 2, 2006 at 3:04 PM
  disqusShortname: null
  timezoneString: " UTC"
  logo: ""
  description_header: Information about <a class='text-grey-darkest' title='Visit
    fixitfaster.com' href='https://www.fixitfaster.com/'>Fix It Faster</a>
  copyrightHolder: Fix It faster Pty Ltd
  eventsPerPage: 10
  iconType: image/png
  icon: /images/clearstatus.png
  description_footer: "<a class='text-grey-darkest' title='Visit fixitfaster.com'
    href='https://www.fixitfaster.com/'>fixitfaster.com</a> "
